name: build-on-commit

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

env:
  PLATFORMS: linux/arm/v7,linux/arm64

permissions:
  packages: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: ghcr.io/${{ github.repository }}
          - dockerfile: ./Dockerfile.nodemo
            image: ghcr.io/${{ github.repository }}-nodemo

    steps:
    - uses: actions/checkout@v3
    -
        name: Build tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
    -
      name: Set up QEMU need for cross-platform building
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ env.PLATFORMS }}
    -
      name: Set up for "docker buildx"
      uses: docker/setup-buildx-action@v2
      with:
        platforms: ${{ env.PLATFORMS }}
    -
      name: Login to GitHub's container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Build image and push image to ghcr.io
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        sbom: false
        provenance: false
        file: ${{ matrix.dockerfile }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          GHCR_REPO=${{ github.repository }}
          GHCR_TAG=${{ steps.meta.outputs.tags }}
          GHCR_PLATFORMS=${{ env.PLATFORMS }}